export const lightTheme = {
  token: {
    fontFamily: "'Helvetica Neue','Inter', sans-serif",
    fontSize: 14,
    colorPrimary: "#28BE46",
    borderRadius: 8,
    colorText: "#000000",
    colorBgHeader: "#ffffff",
    colorBgContainer: "#f3f5f6",
    colorBgLayout: "#ffffff",
    colorBgCard: "#ffffffea",
    controlOutline: "#28BE46",
    controlOutlineWidth: 0.5,
  },
  components: {
    Modal: { borderRadius: 8, colorBgElevated: "#ffffff" },
    Card: {
      taskBg: "#ffffff",
      taskCompletedBg: "#f0f0f0",
      taskText: "#000000",
      taskBorderLow: "green",
      taskBorderMedium: "blue",
      taskBorderHigh: "red",
      taskBorderCompleted: "gray",
    },
    Segmented: {
      itemActiveBg: "#eaf8ef",
      itemHoverBg: "#eaf8ef",
      itemHoverColor: "#28BE46",
      itemSelectedBg: "#28BE46",
      trackBg: "#ffffffea",
      itemSelectedColor: "#000000",
    },
    Input: { colorBgContainer: "#ffffff", colorText: "#000", hoverBorderColor: "#28BE46", activeBorderColor: "#28BE46", controlHeight: 40 },
    Select: { colorBgContainer: "#ffffff", colorText: "#000", controlHeight: 40, optionBg: "#fff", optionSelectedBg: "#eaf8ef", optionSelectedColor: "#28BE46", optionActiveBg: "#f0f0f0", optionActiveColor: "#28BE46" },
    Button: { colorPrimary: "#28BE46", colorPrimaryHover: "#22a53d", colorPrimaryActive: "#1b8c33", controlHeight: 40, borderRadius: 8, boxShadow: "0 2px 6px rgba(0,0,0,0.15)" },
    Checkbox: { colorPrimary: "#28BE46" },
    List: { colorBgContainer: "#ffffff" },
    Spin: { colorPrimary: "#28BE46" },
  },
};

export const darkTheme = {
  token: {
    colorPrimary: "#28BE46",
    colorText: "#ffffff",
    colorBgHeader: "#1a1d20",
    colorBgContainer: "#2E3337",
    colorBgLayout: "#1a1d20",
    colorBgCard: "#2E3337",
    controlOutlineWidth: 0.5,
  },
  components: {
    Modal: { borderRadius: 8, colorBgElevated: "#2E3337" },
    Card: {
      headerBg: "#4a4f52",
      actionsBg: "#4a4f52",
      colorBgContainer: "#4a4f52",
      borderRadius: 8,
      boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
      taskBg: "#4a4f52",
      taskText: "#ffffff",
      taskBorderLow: "green",
      taskBorderMedium: "blue",
      taskBorderHigh: "red",
      taskBorderCompleted: "gray",
    },
    Segmented: { itemActiveBg: "#3a413f", itemHoverBg: "#3a413f", itemHoverColor: "#28BE46", itemSelectedBg: "#28BE46", trackBg: "#3a413f", itemSelectedColor: "#ffffff" },
    Input: { colorBgContainer: "#2E3337", colorText: "#ffffff", hoverBorderColor: "#28BE46", activeBorderColor: "#28BE46", controlHeight: 40 },
    Select: { colorBgContainer: "#2E3337", colorText: "#ffffff", colorTextPlaceholder: "#ffffff", controlHeight: 40, colorBgElevated: "#4a4f52", optionSelectedBg: "#3a413f", optionSelectedColor: "#28BE46", optionActiveBg: "#3a413f", optionActiveColor: "#28BE46" },
    Button: { colorPrimary: "#28BE46", colorPrimaryHover: "#22a53d", colorPrimaryActive: "#1b8c33", controlHeight: 40, borderRadius: 8, boxShadow: "none" },
    Checkbox: { colorPrimary: "#0e9243" },
    List: { colorBgContainer: "#2E3337" },
    Spin: { colorPrimary: "#28BE46" },
  },
};
