export const lightTheme = {
  token: {
    fontFamily: "'Helvetica Neue','Inter', sans-serif",
    fontSize: 14,
    colorPrimary: "#4928beffs",
    borderRadius: 8,
    colorText: "#000000",
    colorBgHeader: "#ffffff",
    colorBgContainer: "#f3f5f6",
    colorBgLayout: "#ffffff",
    colorBgCard: "#ffffffea",
    controlOutline: "#4928beff",
    controlOutlineWidth: 0.5,
  },
  components: {
    Modal: { borderRadius: 8, colorBgElevated: "#ffffff" },
    Card: {
      taskBg: "#ffffff",
      taskCompletedBg: "#f0f0f0",
      taskText: "#000000",
      taskBorderLow: "#28beb1ff",
      taskBorderMedium: "#be6c28ff",
      taskBorderHigh: "#be284eff",
      taskBorderCompleted: "#7d7e7dff",
    },
    Segmented: {
      itemActiveBg: "#eaf8ef",
      itemHoverBg: "#eaf8ef",
      itemHoverColor: "#6750b9ff",
      itemSelectedBg: "#4928beff",
      trackBg: "#ffffffea",
      itemSelectedColor: "#000000",
    },
    Input: { colorBgContainer: "#ffffff", colorText: "#000", hoverBorderColor: "#4928beff", activeBorderColor: "#4928beff", controlHeight: 40 },
    Select: { colorBgContainer: "#ffffff", colorText: "#000", controlHeight: 40, optionBg: "#fff", optionSelectedBg: "#eaf8ef", optionSelectedColor: "#4928beff", optionActiveBg: "#f0f0f0", optionActiveColor: "#4928beff" },
    Button: { colorPrimary: "#9a6decff", colorPrimaryHover: "#6e45bbff", colorPrimaryActive: "#6e45bbff", controlHeight: 40, borderRadius: 8, boxShadow: "0 2px 6px rgba(0,0,0,0.15)" },
    Checkbox: { colorPrimary: "#4928beff" },
    List: { colorBgContainer: "#ffffff" },
    Spin: { colorPrimary: "#4928beff" },  
    Dropdown:{colorBgElevated: "#ffffff", colorPrimary:"#000", colorIcon:"#000"},
      Menu:{itemSelectedBg:"#9f89ecff", itemSelectedColor:'#000'}
  },
};

export const darkTheme = {
  token: {
    colorPrimary: "#4928beff",
    colorText: "#ffffff",
    colorBgHeader: "#1a1d20",
    colorBgContainer: "#2E3337",
    colorBgLayout: "#1a1d20",
    colorBgCard: "#2E3337",
    controlOutlineWidth: 0.5,
  },
  components: {
    Modal: { borderRadius: 8, colorBgElevated: "#2E3337" },
    Card: {
      headerBg: "#4a4f52",
      actionsBg: "#4a4f52",
      colorBgContainer: "#4a4f52",
      borderRadius: 8,
      boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
      taskBg: "#4a4f52",
      taskText: "#ffffff",
      taskBorderLow: "#28beb1ff",
      taskBorderMedium: "#be6c28ff",
      taskBorderHigh: "#be284eff",
      taskBorderCompleted: "#7d7e7dff",
    },
    Segmented: { itemActiveBg: "#3a413f", itemHoverBg: "#3a413f", itemHoverColor: "#4928beff", itemSelectedBg: "#4928beff", trackBg: "#3a413f", itemSelectedColor: "#ffffff" },
    Input: { colorBgContainer: "#2E3337", colorText: "#ffffff", hoverBorderColor: "#4928beff", activeBorderColor: "#4928beff", controlHeight: 40 },
    Select: { colorBgContainer: "#2E3337", colorText: "#ffffff", colorTextPlaceholder: "#ffffff", controlHeight: 40, colorBgElevated: "#4a4f52", optionSelectedBg: "#3a413f", optionSelectedColor: "#4928beff", optionActiveBg: "#3a413f", optionActiveColor: "#4928beff" },
    Button: { colorPrimary: "#8d76e2ff", colorPrimaryHover: "#6e45bbff", colorPrimaryActive: "#6e45bbff", controlHeight: 40, borderRadius: 8, boxShadow: "none" },
    Checkbox: { colorPrimary: "#470e92ff" },
    List: { colorBgContainer: "#2E3337" },
    Spin: { colorPrimary: "#4928beff" }, 
    Dropdown:{colorBgElevated: "#3a413f", colorPrimary:"#ffffff", colorIcon:"#ffffff"},
    Menu:{itemSelectedBg:"#484949ff", itemSelectedColor:'#9f89ecff'}
  },
};
